kind: Service
apiVersion: v1
metadata:
  name: ${artifactId}
  labels:
    app: ${artifactId}
spec:
  type: NodePort
  selector:
    app: ${artifactId}
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${artifactId}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ${artifactId}
        version: v1
    spec:
      containers:
        - name: ${artifactId}
          image: ${artifactId}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 45
      restartPolicy: Always